blog/urls.py
from django.urls import path
from .import views


urlpatterns = [
    path('', views.home, name='home'),
]

homepage/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('news/', include('news.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

news/urls.py
from django.urls import path
from .views import news_index

app_name = 'news'

urlpatterns = [
    path('',news_index,name='index'),
]

blog/models.py
from django.db import models

# Create your models here.

news/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Category(models.Model):
    title = models.CharField(max_length=25)
    excerpt = models.CharField(max_length=160)
    
    class Meta:
        verbose_name_plural = 'categories'
    
    def __str__(self):
        return self.title

class PostModel(models.Model):
    title = models.CharField(max_length=255)
    created_on = models.DateTimeField(auto_now_add=True)
    image = models.ImageField(upload_to='images/')
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    slug = models.SlugField()
    excerpt = models.CharField(max_length=160, blank=True)
    body = models.TextField()
    category = models.ManyToManyField(Category)
    
    class Meta:
        verbose_name_plural = 'posts'
        ordering = ['-created_on']
        
    def __str__(self):
        return self.title

blog/views.py
from django.shortcuts import render
from news.models import PostModel


# Create your views here.
def home(request):
    posts = PostModel.objects.all()[0:3]
    context = {
        'title':'McGill University',
        'posts':posts
    }
    return render(request, 'blog/home.html', context)

news/views.py
from django.shortcuts import render
from .models import PostModel, Category

# Create your views here.
def news_index(request):
    posts = PostModel.objects.all()[0:3]
    category = Category.objects.all()
    context = {
        'title': 'NewsRoom',
        'posts':posts,
        'category':category
    }
    return render(request, 'news/index.html', context)

blog/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>McGill University</title>
    <script src="https://cdn.tailwindcss.com"></script>
</head>
<body>
    
    <div>
        {% block content %}
        {% endblock %}
    </div>
    
</body>
</html>

blog/templates/blog/about.html
{% extends 'base.html' %}

{% block content %}
{% endblock %}

blog/templates/blog/home.html
{% extends 'base.html' %}

{% block content %}
{% include  'header.html' %}

<section class="w-full  bg-white">
    <div class="my-4 mx-6 grid grid-cols-3 bg-gray-100 gap-3 rounded-xl" >
        {% for post in posts %}
        <div class=" mx-4 my-2 py-2 px-2 border-2 border-gray-100 rounded-xl " >
            <div>
                <img src="{{post.image.url}}" class="rounded-t-xl h-64" >
            </div>
           
            <a href="#"  > <h1 class="text-2xl bg-red-500 text-white rounded-b-xl "> {{post.title}} </h1></a>
        </div>
        {%endfor %}
        <div>
            <a href="{% url 'news:index' %}" class="text-2xl px-6 py-2 text-white bg-red-500">Read More</a>
        </div>
    </div>
   
</section>
 
{% include 'footer.html' %}
{% endblock %}

blog/templates/footer.html
<footer class="container w-full">
    <div class="grid grid-cols-3 gap-3 bg-slate-800 text-cyan-50">
        <div class="ml-10 my-4">
            <h2 class="text-2xl">For current students</h2>
            <li class="list-none py-4" >
                <a href="#">Email(Outlook)</a>
            </li>
            <li class="list-none" >
                <a  href="#">MyCourses</a>
            </li>
            <li class="list-none py-4" >
                <a href="#">Minerva</a>
            </li>
            <li class="list-none" >
                <a  href="#">MuMcGill</a>
            </li>
            <li class="list-none py-4" >
                <a  href="#">Library</a>
            </li>
            <li class="list-none" >
                <a  href="#">Programs and Courses</a>
            </li>
            <li class="list-none py-4" >
                <a  href="#">Resources and Services</a>
            </li>
        </div>
        <div class="my-4"  >
            <h2 class="text-2xl">For faculty & staff</h2>
            <li class="list-none py-4" >
                <a href="#">Email(Outlook)</a>
            </li>
            <li class="list-none" >
                <a  href="#">Minerva</a>
            </li>
            <li class="list-none py-4" >
                <a href="#">Workday</a>
            </li>
            <li class="list-none" >
                <a  href="#">MyCourses</a>
            </li>
            <li class="list-none py-4" >
                <a  href="#">Staff Directory</a>
            </li>
            <li class="list-none" >
                <a  href="#">Human Resources</a>
            </li>
            <li class="list-none py-4" >
                <a  href="#">MyMcGill</a>
            </li>
            <li class="list-none py-4" >
                <a  href="#">Banner INB</a>
            </li>
            <li class="list-none py-4" >
                <a  href="#">Resources and Services</a>
            </li>
            <li class="list-none py-4" >
                <a  href="#">Teaching and Learning Services</a>
            </li>
        </div>
        <div class="ml-10 my-4">
            <h2 class="text-2xl">For alumni & friends</h2>
            <li class="list-none py-4" >
                <a href="#">Alumini Email</a>
            </li>
            <li class="list-none" >
                <a  href="#"> The McGill alumni network</a>
            </li>
            <li class="list-none py-4" >
                <a href="#"> Attend an event</a>
            </li>
            <li class="list-none" >
                <a  href="#"> Volunteer</a>
            </li>
            <li class="list-none py-4" >
                <a  href="#">Alumini Benefits</a>
            </li>
            <li class="list-none" >
                <a  href="#">Give Back</a>
            </li>
            <li class="list-none py-4" >
                <a  href="#"> McGill News alumni magazine </a>
            </li>
            <li class="list-none py-4 text-base" >
                <a  href="#"> Transcripts </a>
            </li>
        </div>
    </div>
    <div class="grid grid-cols-4 gap-4 bg-gray-950 text-cyan-50 border-b border-white">
        <div class="my-4 mx-2 ml-8" >
            <h2 class="text-2xl py-4" >In an emergency</h2>
            <p class="py-2"> <a  href="#">514-398-3000 (downtown campus)</a> </p>
            <p class="py-2"> <a  href="#">514-398-7777 (Macdonald campus)</a> </p>
        </div>
        <div class="my-4 mx-2"> 
            <h2 class="text-2xl"> Visit </h2>
            <li class="list-none py-2">
                <a href="#">Take the virtual tour</a>
            </li>
            <li class="list-none py-2">
                <a href="#">Campus map</a>
            </li>
            <li class="list-none py-2">
                <a href="#">845 Sherbrooke Street West</a>
            </li>
            <li class="list-none py-2">
                <a href="#">Montréal (Québec)  H3A 0G4</a>
            </li>
        </div>
        <div class="my-4 mx-2">
            <h2 class="text-2xl"> Get in touch </h2>
            <li class="list-none py-2">
                <a href="#">Contact us</a>
            </li>
            <li class="list-none py-2">
                <a href="#">AskMcGill</a>
            </li>
            <li class="list-none py-2">
                <a href="#">Hire a student</a>
            </li>
            <li class="list-none py-2">
                <a href="#">Media Relations</a>
            </li>
            <li class="list-none py-2">
                <a href="#">Community Engagement</a>
            </li>
        </div>
        <div class="my-4 mx-2">
            <h2 class="text-2xl" > Explore </h2>
            <li class="list-none py-2">
                <a href="#">Careers</a>
            </li>
            <li class="list-none py-2">
                <a href="#">News</a>
            </li>
            <li class="list-none py-2">
                <a href="#">Events</a>
            </li>
        </div>
    </div>
    <div class=" flex flex-row bg-gray-950 text-cyan-50 h-16 items-center justify-center " >
        <h1 class="pl-4 py-4 px-6">McGill</h1>
        <p class="py-4" > Copyright © 2023 McGill University. </p>
        <li class="list-none py-4 px-8">
            <a href="#">Accessibility</a>
        </li>
        <li class="list-none py-4 px-8">
            <a href="#">Privacy Notice</a>
        </li>
        <li class="list-none py-4 px-8">
            <a href="#">Privacy notice</a>
        </li>
    </div>
</footer>

blog/templates/header.html
<header class="bg-white h-20 ">
    <nav class="flex flex-row mx-4 h-16 shadow-lg ">
        <div class="basis-1/4 ml-4">
            <h1 class="text-2xl text-cyan-50 py-2 bg- w-28 h-16 bg-red-800 text-center ">McGill</h1>
        </div>
        <div class="basis-3/4">
            <ul class="flex">
                <li class=" text-lg px-6 py-4 font-normal">
                    <a href="">Admissions</a>
                </li>
                <li class="px-6 py-4 font-normal text-lg">
                    <a href="">Student Life</a>
                </li>
                <li class="px-6 py-4 font-normal text-lg">
                    <a href="">Why Montreal</a>
                </li>
                <li class="px-6 py-4 font-normal text-lg">
                    <a href="">About McGill</a>
                </li>
            </ul>
        </div>
    </nav>
</header>

news/templates/news/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://cdn.tailwindcss.com"></script>
    <title> {% block title %}  {%endblock %}| McGill University </title>
</head>
<body>
    {% include 'news/header.html' %}
    {% block content %}

    {% endblock %}
    {% include 'news/footer.html' %}
</body>
</html>

news/templates/news/detail.html
{% extends 'blog/base.html' %}

news/templates/news/footer.html
<footer class="w-full">
    <div class="flex flex-row">
        <div class="grid grid-cols-4 bg-gray-100 gap-5">
            <div class="my-4 mx-4 px-6 py-6">
                <h1 class=" text-2xl font-bold py-2">Institutional Communications</h1>
                <p>James Administration Building
                    845 Sherbrooke Street West
                    Montreal, Quebec H3A 0G4
                    514-398-6693</p>
                <a href="#">Contact info</a>
            </div>
            <div class="my-4 mx-4 px-6 py-6">
                <h1 class=" text-2xl font-bold py-2">McGill news</h1>
                
                    <a href="#"> Campus news</a> <br>
                    <a href="#"> News releases </a> <br>
                    <a href="#"> McGill dans la ville </a> <br>
                    <a href="#"> Office of the Principal </a> <br>
                    <a href="#"> Office of the Provost </a> <br>
            
            </div>
            <div class="my-4 mx-4 px-6 py-6">
                <h1 class=" text-2xl font-bold py-2">Institutional Communications</h1>
                <li class="list-none">
                    <a href="#">For Faculty and staff</a>
                </li>
                <li class="list-none">
                    <a href="#">For Faculty Journalists</a>
                </li>
                <li class="list-none">
                    <a href="#">McGill expert guide</a>
                </li>
                <li class="list-none">
                    <a href="#">Ask McGill</a>
                </li>
            </div>
            <div class="my-4 mx-4 px-6 py-6">
                <h1 class=" text-2xl font-bold py-2">McGill Facts</h1>
                <li class="list-none"> <a href="#">About McGill</a> </li>
                <li class="list-none"> <a href="#">Quick facts</a> </li>
                <li class="list-none"> <a href="#">History</a> </li>
                <li class="list-none"> <a href="#">Administration</a> </li>
            </div>
        </div>
    </div>
    <div class="bg-gray-800 w-full flex justify-between  px-6 py-6">
        <a href="https://www.mcgill.ca/" class="text-white text-2xl border-2 hover:bg-lime-500  px-2 pl-2 ">McGill</a>
        <p class="text-center text-white  inline-block">
            Copyright © 2023 McGill University
        </p>
        <p class="pr-8">
            <a href="#" class="text-white">Accessibility <span> <a href="#" class="border-2 px-2 text-white">login</a> </span> </a>
        </p>
    </div>
     
</footer>

news/templates/news/header.html
<header class="w-full">
    <nav class="grid grid-row-2">
        <div class="bg-gray-100 flex justify-between " >
            <div class="flex items-center  mt-6 mb-4 pb-4 ml-20 pl-16" >
                <li class="list-none">
                    <a href="#">
                        <h1 class="text-3xl font-bold text-red-500 border-r-2 border-gray-500 px-2 ">McGill</h1>
                    </a>
                </li> 
                <li class="list-none px-3">
                    <a href="#">
                        <h1 class="text-2xl  text-gray-800  ">NewsRoom</h1>
                    </a>
                    <p>Institutional Communications</p>
                </li> 
            </div>
            <div class=" flex justify-end pr-8">
                <form action="#" method="post" class="p-6" >
                    <input type="search" placeholder="search" class="py-2 px-2 inline-block"  >
                   <span> <button type="button" class="bg-red-300 px-3 py-2" >Submit</button></span> 
                </form>
            </div>
            
        </div>
        <div class="bg-gray-800 text-white justify-start" > 
            <ul class="flex ml-28 pl-10">
                <li class="list-none p-2 hover:bg-gray-900" >
                    <a href="#">For Journalists</a>
                </li>
                <li class="list-none p-2 hover:bg-gray-900" >
                    <a href="#">For Faculty and Staff</a>
                </li>
                <li class="list-none p-2 hover:bg-gray-900" >
                    <a href="#">Expert Guide</a>
                </li>
                <li class="list-none p-2 hover:bg-gray-900" >
                    <a href="#">Contact us</a>
                </li>
            </ul>
        </div>
    </nav>
</header>

news/templates/news/index.html
{% extends 'news/base.html' %}
{% load static %}

{% block title %} {{title}} {% endblock %}

{% block content %}
<section class="w-full ">
    <div class="my-4 mx-6 grid grid-cols-3 bg-gray-200 gap-3 rounded-xl" >
        {% for post in posts %}
        <div class=" mx-4 my-2 py-2 px-2 border-2 border-gray-100 rounded-xl " >
            <div>
                <img src="{{post.image.url}}" class="rounded-t-xl h-64" >
            </div>
           
            <a href="#"  > <h1 class="text-2xl bg-red-500 text-white rounded-b-xl "> {{post.title}} </h1></a>
        </div>
        {%endfor %}
    </div>
</section>
{% endblock %}